import { createSlice } from "@reduxjs/toolkit"; // Import createSlice from Redux Toolkit

// Define the user slice
const userSlice = createSlice({
  name: "user", // Slice name
  initialState: { // Initialize state
    userId: null, // User ID starts as null
    message: "" // Message starts as an empty string
  },
  reducers: { // Define reducers for this slice
    setUser: (state, action) => { // Action type: setUser    //state describing our current state
      state.userId = action.payload.id; // Update userId from action payload
    },
  },
});

// Export actions generated by createSlice
export const { setUser } = userSlice.actions;

// Export the reducer to be used in the store
export default userSlice.reducer;
